name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NODE_ENV: test
  DB_TYPE: mariadb
  DB_HOST: localhost
  DB_PORT: 3306
  DB_USERNAME: rootchallenge
  DB_PASSWORD: rootchallenge
  DB_DATABASE: challenge
  SECRET_KEY: challenge

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:latest
        env:
          MYSQL_USER: rootchallenge
          MYSQL_PASSWORD: rootchallenge
          MARIADB_ROOT_PASSWORD: rootchallenge
          MYSQL_DATABASE: challenge
        ports:
          - 3306:3306

        options: >-
          --health-cmd "mysqladmin ping -urootchallenge -prootchallenge"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'latest'

      - name: Install dependencies
        run: npm install

      - name: Run database migrations
        run: npm run migrate:run

      - name: Run tests
        run: npm test
